# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motion_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13motion_server.proto\x12\rmotion_server\"Q\n\x10SetMotionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\x0e\n\x06repeat\x18\x03 \x01(\x08\x12\r\n\x05\x63lear\x18\x04 \x01(\x08\"!\n\x0eSetMotionReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x14\n\x12\x43learMotionRequest\"#\n\x10\x43learMotionReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb9\x01\n\x13MotionServerService\x12M\n\tSetMotion\x12\x1f.motion_server.SetMotionRequest\x1a\x1d.motion_server.SetMotionReply\"\x00\x12S\n\x0b\x43learMotion\x12!.motion_server.ClearMotionRequest\x1a\x1f.motion_server.ClearMotionReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'motion_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SETMOTIONREQUEST']._serialized_start=38
  _globals['_SETMOTIONREQUEST']._serialized_end=119
  _globals['_SETMOTIONREPLY']._serialized_start=121
  _globals['_SETMOTIONREPLY']._serialized_end=154
  _globals['_CLEARMOTIONREQUEST']._serialized_start=156
  _globals['_CLEARMOTIONREQUEST']._serialized_end=176
  _globals['_CLEARMOTIONREPLY']._serialized_start=178
  _globals['_CLEARMOTIONREPLY']._serialized_end=213
  _globals['_MOTIONSERVERSERVICE']._serialized_start=216
  _globals['_MOTIONSERVERSERVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
