# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13speech_server.proto\x12\rspeech_server\"*\n\x18SetRecognitionFlgRequest\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\")\n\x16SetRecognitionFlgReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32z\n\x13SpeechServerService\x12\x63\n\x11SetRecognitionFlg\x12\'.speech_server.SetRecognitionFlgRequest\x1a%.speech_server.SetRecognitionFlgReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speech_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SETRECOGNITIONFLGREQUEST']._serialized_start=38
  _globals['_SETRECOGNITIONFLGREQUEST']._serialized_end=80
  _globals['_SETRECOGNITIONFLGREPLY']._serialized_start=82
  _globals['_SETRECOGNITIONFLGREPLY']._serialized_end=123
  _globals['_SPEECHSERVERSERVICE']._serialized_start=125
  _globals['_SPEECHSERVERSERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
