# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13speech_server.proto\x12\rspeech_server\"%\n\x13ToggleSpeechRequest\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\"$\n\x11ToggleSpeechReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32k\n\x13SpeechServerService\x12T\n\x0cToggleSpeech\x12\".speech_server.ToggleSpeechRequest\x1a .speech_server.ToggleSpeechReplyb\x06proto3')



_TOGGLESPEECHREQUEST = DESCRIPTOR.message_types_by_name['ToggleSpeechRequest']
_TOGGLESPEECHREPLY = DESCRIPTOR.message_types_by_name['ToggleSpeechReply']
ToggleSpeechRequest = _reflection.GeneratedProtocolMessageType('ToggleSpeechRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOGGLESPEECHREQUEST,
  '__module__' : 'speech_server_pb2'
  # @@protoc_insertion_point(class_scope:speech_server.ToggleSpeechRequest)
  })
_sym_db.RegisterMessage(ToggleSpeechRequest)

ToggleSpeechReply = _reflection.GeneratedProtocolMessageType('ToggleSpeechReply', (_message.Message,), {
  'DESCRIPTOR' : _TOGGLESPEECHREPLY,
  '__module__' : 'speech_server_pb2'
  # @@protoc_insertion_point(class_scope:speech_server.ToggleSpeechReply)
  })
_sym_db.RegisterMessage(ToggleSpeechReply)

_SPEECHSERVERSERVICE = DESCRIPTOR.services_by_name['SpeechServerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOGGLESPEECHREQUEST._serialized_start=38
  _TOGGLESPEECHREQUEST._serialized_end=75
  _TOGGLESPEECHREPLY._serialized_start=77
  _TOGGLESPEECHREPLY._serialized_end=113
  _SPEECHSERVERSERVICE._serialized_start=115
  _SPEECHSERVERSERVICE._serialized_end=222
# @@protoc_insertion_point(module_scope)
