# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='speech_server.proto',
  package='speech_server',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13speech_server.proto\x12\rspeech_server\"%\n\x13ToggleSpeechRequest\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\"$\n\x11ToggleSpeechReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32k\n\x13SpeechServerService\x12T\n\x0cToggleSpeech\x12\".speech_server.ToggleSpeechRequest\x1a .speech_server.ToggleSpeechReplyb\x06proto3'
)




_TOGGLESPEECHREQUEST = _descriptor.Descriptor(
  name='ToggleSpeechRequest',
  full_name='speech_server.ToggleSpeechRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable', full_name='speech_server.ToggleSpeechRequest.enable', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=75,
)


_TOGGLESPEECHREPLY = _descriptor.Descriptor(
  name='ToggleSpeechReply',
  full_name='speech_server.ToggleSpeechReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='speech_server.ToggleSpeechReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['ToggleSpeechRequest'] = _TOGGLESPEECHREQUEST
DESCRIPTOR.message_types_by_name['ToggleSpeechReply'] = _TOGGLESPEECHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ToggleSpeechRequest = _reflection.GeneratedProtocolMessageType('ToggleSpeechRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOGGLESPEECHREQUEST,
  '__module__' : 'speech_server_pb2'
  # @@protoc_insertion_point(class_scope:speech_server.ToggleSpeechRequest)
  })
_sym_db.RegisterMessage(ToggleSpeechRequest)

ToggleSpeechReply = _reflection.GeneratedProtocolMessageType('ToggleSpeechReply', (_message.Message,), {
  'DESCRIPTOR' : _TOGGLESPEECHREPLY,
  '__module__' : 'speech_server_pb2'
  # @@protoc_insertion_point(class_scope:speech_server.ToggleSpeechReply)
  })
_sym_db.RegisterMessage(ToggleSpeechReply)



_SPEECHSERVERSERVICE = _descriptor.ServiceDescriptor(
  name='SpeechServerService',
  full_name='speech_server.SpeechServerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=115,
  serialized_end=222,
  methods=[
  _descriptor.MethodDescriptor(
    name='ToggleSpeech',
    full_name='speech_server.SpeechServerService.ToggleSpeech',
    index=0,
    containing_service=None,
    input_type=_TOGGLESPEECHREQUEST,
    output_type=_TOGGLESPEECHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPEECHSERVERSERVICE)

DESCRIPTOR.services_by_name['SpeechServerService'] = _SPEECHSERVERSERVICE

# @@protoc_insertion_point(module_scope)
