# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import style_bert_vits_server_pb2 as style__bert__vits__server__pb2


class StyleBertVitsServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetText = channel.unary_unary(
                '/style_bert_vits_server.StyleBertVitsServerService/SetText',
                request_serializer=style__bert__vits__server__pb2.SetTextRequest.SerializeToString,
                response_deserializer=style__bert__vits__server__pb2.SetTextReply.FromString,
                )
        self.SetParam = channel.unary_unary(
                '/style_bert_vits_server.StyleBertVitsServerService/SetParam',
                request_serializer=style__bert__vits__server__pb2.SetParamRequest.SerializeToString,
                response_deserializer=style__bert__vits__server__pb2.SetParamReply.FromString,
                )
        self.InterruptVoice = channel.unary_unary(
                '/style_bert_vits_server.StyleBertVitsServerService/InterruptVoice',
                request_serializer=style__bert__vits__server__pb2.InterruptVoiceRequest.SerializeToString,
                response_deserializer=style__bert__vits__server__pb2.InterruptVoiceReply.FromString,
                )
        self.SetVoicePlayFlg = channel.unary_unary(
                '/style_bert_vits_server.StyleBertVitsServerService/SetVoicePlayFlg',
                request_serializer=style__bert__vits__server__pb2.SetVoicePlayFlgRequest.SerializeToString,
                response_deserializer=style__bert__vits__server__pb2.SetVoicePlayFlgReply.FromString,
                )


class StyleBertVitsServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InterruptVoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVoicePlayFlg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StyleBertVitsServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetText': grpc.unary_unary_rpc_method_handler(
                    servicer.SetText,
                    request_deserializer=style__bert__vits__server__pb2.SetTextRequest.FromString,
                    response_serializer=style__bert__vits__server__pb2.SetTextReply.SerializeToString,
            ),
            'SetParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SetParam,
                    request_deserializer=style__bert__vits__server__pb2.SetParamRequest.FromString,
                    response_serializer=style__bert__vits__server__pb2.SetParamReply.SerializeToString,
            ),
            'InterruptVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.InterruptVoice,
                    request_deserializer=style__bert__vits__server__pb2.InterruptVoiceRequest.FromString,
                    response_serializer=style__bert__vits__server__pb2.InterruptVoiceReply.SerializeToString,
            ),
            'SetVoicePlayFlg': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVoicePlayFlg,
                    request_deserializer=style__bert__vits__server__pb2.SetVoicePlayFlgRequest.FromString,
                    response_serializer=style__bert__vits__server__pb2.SetVoicePlayFlgReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'style_bert_vits_server.StyleBertVitsServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StyleBertVitsServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/style_bert_vits_server.StyleBertVitsServerService/SetText',
            style__bert__vits__server__pb2.SetTextRequest.SerializeToString,
            style__bert__vits__server__pb2.SetTextReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/style_bert_vits_server.StyleBertVitsServerService/SetParam',
            style__bert__vits__server__pb2.SetParamRequest.SerializeToString,
            style__bert__vits__server__pb2.SetParamReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InterruptVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/style_bert_vits_server.StyleBertVitsServerService/InterruptVoice',
            style__bert__vits__server__pb2.InterruptVoiceRequest.SerializeToString,
            style__bert__vits__server__pb2.InterruptVoiceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVoicePlayFlg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/style_bert_vits_server.StyleBertVitsServerService/SetVoicePlayFlg',
            style__bert__vits__server__pb2.SetVoicePlayFlgRequest.SerializeToString,
            style__bert__vits__server__pb2.SetVoicePlayFlgReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
