# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voice_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12voice_server.proto\x12\x0cvoice_server"\x1e\n\x0eSetTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t"\x1f\n\x0cSetTextReply\x12\x0f\n\x07success\x18\x01 \x01(\x08"\xd4\x01\n\x1cSetStyleBertVitsParamRequest\x12\x17\n\nmodel_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08model_id\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x13\n\x06length\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x12\n\x05style\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x19\n\x0cstyle_weight\x18\x05 \x01(\tH\x04\x88\x01\x01\x42\r\n\x0b_model_nameB\x0b\n\t_model_idB\t\n\x07_lengthB\x08\n\x06_styleB\x0f\n\r_style_weight"-\n\x1aSetStyleBertVitsParamReply\x12\x0f\n\x07success\x18\x01 \x01(\x08"e\n\x17SetVoicevoxParamRequest\x12\x14\n\x07speaker\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x0bspeed_scale\x18\x02 \x01(\x02H\x01\x88\x01\x01\x42\n\n\x08_speakerB\x0e\n\x0c_speed_scale"(\n\x15SetVoicevoxParamReply\x12\x0f\n\x07success\x18\x01 \x01(\x08"\x17\n\x15InterruptVoiceRequest"&\n\x13InterruptVoiceReply\x12\x0f\n\x07success\x18\x01 \x01(\x08"%\n\x16SetVoicePlayFlgRequest\x12\x0b\n\x03\x66lg\x18\x01 \x01(\x08"\'\n\x14SetVoicePlayFlgReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xdf\x03\n\x12VoiceServerService\x12\x43\n\x07SetText\x12\x1c.voice_server.SetTextRequest\x1a\x1a.voice_server.SetTextReply\x12m\n\x15SetStyleBertVitsParam\x12*.voice_server.SetStyleBertVitsParamRequest\x1a(.voice_server.SetStyleBertVitsParamReply\x12^\n\x10SetVoicevoxParam\x12%.voice_server.SetVoicevoxParamRequest\x1a#.voice_server.SetVoicevoxParamReply\x12X\n\x0eInterruptVoice\x12#.voice_server.InterruptVoiceRequest\x1a!.voice_server.InterruptVoiceReply\x12[\n\x0fSetVoicePlayFlg\x12$.voice_server.SetVoicePlayFlgRequest\x1a".voice_server.SetVoicePlayFlgReplyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "voice_server_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _globals["_SETTEXTREQUEST"]._serialized_start = 36
    _globals["_SETTEXTREQUEST"]._serialized_end = 66
    _globals["_SETTEXTREPLY"]._serialized_start = 68
    _globals["_SETTEXTREPLY"]._serialized_end = 99
    _globals["_SETSTYLEBERTVITSPARAMREQUEST"]._serialized_start = 102
    _globals["_SETSTYLEBERTVITSPARAMREQUEST"]._serialized_end = 314
    _globals["_SETSTYLEBERTVITSPARAMREPLY"]._serialized_start = 316
    _globals["_SETSTYLEBERTVITSPARAMREPLY"]._serialized_end = 361
    _globals["_SETVOICEVOXPARAMREQUEST"]._serialized_start = 363
    _globals["_SETVOICEVOXPARAMREQUEST"]._serialized_end = 464
    _globals["_SETVOICEVOXPARAMREPLY"]._serialized_start = 466
    _globals["_SETVOICEVOXPARAMREPLY"]._serialized_end = 506
    _globals["_INTERRUPTVOICEREQUEST"]._serialized_start = 508
    _globals["_INTERRUPTVOICEREQUEST"]._serialized_end = 531
    _globals["_INTERRUPTVOICEREPLY"]._serialized_start = 533
    _globals["_INTERRUPTVOICEREPLY"]._serialized_end = 571
    _globals["_SETVOICEPLAYFLGREQUEST"]._serialized_start = 573
    _globals["_SETVOICEPLAYFLGREQUEST"]._serialized_end = 610
    _globals["_SETVOICEPLAYFLGREPLY"]._serialized_start = 612
    _globals["_SETVOICEPLAYFLGREPLY"]._serialized_end = 651
    _globals["_VOICESERVERSERVICE"]._serialized_start = 654
    _globals["_VOICESERVERSERVICE"]._serialized_end = 1133
# @@protoc_insertion_point(module_scope)
