# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voicevox_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15voicevox_server.proto\x12\x0fvoicevox_server""\n\x12SetVoicevoxRequest\x12\x0c\n\x04text\x18\x01 \x01(\t"#\n\x10SetVoicevoxReply\x12\x0f\n\x07success\x18\x01 \x01(\x08"\x1a\n\x18InterruptVoicevoxRequest")\n\x16InterruptVoicevoxReply\x12\x0f\n\x07success\x18\x01 \x01(\x08"%\n\x16SetVoicePlayFlgRequest\x12\x0b\n\x03\x66lg\x18\x01 \x01(\x08"\'\n\x14SetVoicePlayFlgReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xba\x02\n\x15VoicevoxServerService\x12U\n\x0bSetVoicevox\x12#.voicevox_server.SetVoicevoxRequest\x1a!.voicevox_server.SetVoicevoxReply\x12g\n\x11InterruptVoicevox\x12).voicevox_server.InterruptVoicevoxRequest\x1a\'.voicevox_server.InterruptVoicevoxReply\x12\x61\n\x0fSetVoicePlayFlg\x12\'.voicevox_server.SetVoicePlayFlgRequest\x1a%.voicevox_server.SetVoicePlayFlgReplyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "voicevox_server_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _globals["_SETVOICEVOXREQUEST"]._serialized_start = 42
    _globals["_SETVOICEVOXREQUEST"]._serialized_end = 76
    _globals["_SETVOICEVOXREPLY"]._serialized_start = 78
    _globals["_SETVOICEVOXREPLY"]._serialized_end = 113
    _globals["_INTERRUPTVOICEVOXREQUEST"]._serialized_start = 115
    _globals["_INTERRUPTVOICEVOXREQUEST"]._serialized_end = 141
    _globals["_INTERRUPTVOICEVOXREPLY"]._serialized_start = 143
    _globals["_INTERRUPTVOICEVOXREPLY"]._serialized_end = 184
    _globals["_SETVOICEPLAYFLGREQUEST"]._serialized_start = 186
    _globals["_SETVOICEPLAYFLGREQUEST"]._serialized_end = 223
    _globals["_SETVOICEPLAYFLGREPLY"]._serialized_start = 225
    _globals["_SETVOICEPLAYFLGREPLY"]._serialized_end = 264
    _globals["_VOICEVOXSERVERSERVICE"]._serialized_start = 267
    _globals["_VOICEVOXSERVERSERVICE"]._serialized_end = 581
# @@protoc_insertion_point(module_scope)
